name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build -A x64
      - name: Build
        run: cmake --build build --config Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/cs2esp.exe
          generate_release_notes: true
